1.c =>sum of all the elements of the array.
2.c =>average of elements of array.
3.c => squre of each elemnets of array.
4.c => gcd of whole array.
5.c => lcm of whole array.
6.c => find large elements of elements.
7.c => reverse of an array.
8.c => array is pallindrome or not.
9.c => program to arrange array elements in acsending order.
10.c=>delete an element from array
11.c=>delete multiple elements from array.
12.c=>large and small elements in array.
13.c=>insert an element into array.
12.c=>insertion sort
13.c=>binary search
14.c=>selection sort
15.c=>min and max elements among array.
16.c=>remove duplicate elements from array.
17.c=>merge two array into single array.
18.c=>two arrays are pallindrome or not.
19.c=>merge two array by using pdf.
20.c=>
